// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDq3vNVjuiTu7qKdLyr6Y3M1LUPdVYCw',
    appId: '1:957442523918:web:a13fe7389cbffb9ebe4d5f',
    messagingSenderId: '957442523918',
    projectId: 'mywallet-5bdb3',
    authDomain: 'mywallet-5bdb3.firebaseapp.com',
    storageBucket: 'mywallet-5bdb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDQo0ujgRmq_yxjrZSIqM1DCpSF1jBO3o',
    appId: '1:957442523918:android:78df9de834812f9fbe4d5f',
    messagingSenderId: '957442523918',
    projectId: 'mywallet-5bdb3',
    storageBucket: 'mywallet-5bdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMfLN6-TVgqQHeRVDP0_S7V7haTXvKPQ',
    appId: '1:957442523918:ios:241a485b791e1185be4d5f',
    messagingSenderId: '957442523918',
    projectId: 'mywallet-5bdb3',
    storageBucket: 'mywallet-5bdb3.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMfLN6-TVgqQHeRVDP0_S7V7haTXvKPQ',
    appId: '1:957442523918:ios:241a485b791e1185be4d5f',
    messagingSenderId: '957442523918',
    projectId: 'mywallet-5bdb3',
    storageBucket: 'mywallet-5bdb3.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsDq3vNVjuiTu7qKdLyr6Y3M1LUPdVYCw',
    appId: '1:957442523918:web:a4a07ea31c8a9be1be4d5f',
    messagingSenderId: '957442523918',
    projectId: 'mywallet-5bdb3',
    authDomain: 'mywallet-5bdb3.firebaseapp.com',
    storageBucket: 'mywallet-5bdb3.firebasestorage.app',
  );
}
