// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3MG5IWarDhpT73dSFZc6quzvLDhcPWQ',
    appId: '1:435257793979:web:a240cb7da62520cde9b89e',
    messagingSenderId: '435257793979',
    projectId: 'mywallet-abf4b',
    authDomain: 'mywallet-abf4b.firebaseapp.com',
    storageBucket: 'mywallet-abf4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3MG5IWarDhpT73dSFZc6quzvLDhcPWQ',
    appId: '1:435257793979:android:b223ba96565ae220e9b89e',
    messagingSenderId: '435257793979',
    projectId: 'mywallet-abf4b',
    storageBucket: 'mywallet-abf4b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3MG5IWarDhpT73dSFZc6quzvLDhcPWQ',
    appId: '1:435257793979:ios:18a9878bc5a6ad40e9b89e',
    messagingSenderId: '435257793979',
    projectId: 'mywallet-abf4b',
    storageBucket: 'mywallet-abf4b.firebasestorage.app',
    iosBundleId: 'my-wallet.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcrHh-3zo9SD05GCEJU6RqDGk6_duGHMA',
    appId: '1:435257793979:web:a240cb7da62520cde9b89e',
    messagingSenderId: '435257793979',
    projectId: 'mywallet-abf4b',
    authDomain: 'mywallet-abf4b.firebaseapp.com',
    storageBucket: 'mywallet-abf4b.firebasestorage.app',
  );

}